### ISSUE TITLE
finetuning part is missing

### ISSUE THREAD

**Issue by panovr** [mrgloom/kaggle-dogs-vs-cats-solution#1]
The README says there is a finetuning folder, but it is missing currently.

**Comment by mrgloom** [comment]
It's ready, I will update it in few days.

**Comment by mrgloom** [comment]
Done
https://github.com/mrgloom/kaggle-dogs-vs-cats-solution/tree/master/finetuning

**Comment by panovr** [comment]
:thumbsup:
