### ISSUE TITLE
 train and validation dataset  for squeezenet .

### ISSUE THREAD

**Issue by deepnarainsingh** [mrgloom/kaggle-dogs-vs-cats-solution#3]
could you share the train and validation data used for squeezenet , i need to replicate your work.

**Comment by mrgloom** [comment]
Simplest way will be to to create database in DIGITS from kaggle data in my case it was 80% train 20% test split with image sqeeze to 256x256.

**Comment by deepnarainsingh** [comment]
thanks for your answer.
I am not able to replicate the squeezenet results for a regression task while the alexnet gives a loss much better than squeezenet , can you please help on the same.

**Comment by mrgloom** [comment]
Are you solving our own regression problem or you can't reproduce Cats vs Dogs kaggle competition?
