### ISSUE TITLE
mean.binaryproto

### ISSUE THREAD

**Issue by Hanimiao** [mrgloom/kaggle-dogs-vs-cats-solution#4]
Hello, can you tell me how to use the GoogLeNet network structure to produce mean.binaryproto

**Comment by mrgloom** [comment]
`mean.binaryproto` is mean image or mean [R,G,B] and computed from images, if you are using `DIGITS` it's created after creating dataset in lmdb/leveldb format.

**Comment by Jacobtom** [comment]
I used the caffe framework, the first step produced train_lmdb, val_db, but I do not know how to generate the mean.binaryproto file because my computer did not install digist, I used the mean.binaryproto in the googlenet folder directly,when i start training the model by executing the command below: /home/ubuntu/caffe/build/tools/caffe train --solver /home/ubuntu/googlenet/solver.prototxt 2>&1 | tee /home/ubuntu/train.log,The terminal displays the following information:Check failed:mdb_status == 0(2 vs.0) No such file or directory.

**Comment by mrgloom** [comment]
[This tool](https://github.com/BVLC/caffe/blob/master/tools/compute_image_mean.cpp) that you should have under tools of caffe base dir will help you to create mean file.
I have it under `caffe/distribute/bin/compute_image_mean.bin`

**Comment by Jacobtom** [comment]
Hello, can you tell me how to categorize images with caffe framework and googlenet network?  i really don't know the role of these documents, can u give detailed steps to explain ah?thank you so much

**Comment by mrgloom** [comment]
Do you mean classification task?
https://github.com/NVIDIA/DIGITS/blob/master/docs/GettingStarted.md
https://github.com/NVIDIA/DIGITS/blob/master/docs/ImageFolderFormat.md
https://github.com/NVIDIA/DIGITS/tree/master/examples/classification

**Comment by Jacobtom** [comment]
My computer did not install digist，Can you give me a detailed step in using the caffe framework and the googlenet network for image sorting?

**Comment by mrgloom** [comment]
What do you mean by sorting?

If you want to use C++ API for classification you can look at
https://github.com/BVLC/caffe/tree/master/examples/cpp_classification

**Comment by Jacobtom** [comment]
omnisky@omnisky:~/GoogLeNet$ python average_results.py
/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:73: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False) and get the /home/omnisky/GoogLeNet/submissions/kaggle_submit_probability_avr.csv
id	label
1	nan
2	nan
3	nan
4	nan
5	nan
6	nan
7	nan
8	nan
9	nan
10	nan
11	nan
12	nan
13	nan
14	nan
15	nan
16	nan
17	nan
18	nan
19	nan
20	nan
21	nan
22	nan
23	nan
24	nan
25	nan
26	nan
27	nan
28	nan
29	nan
30	nan
31	nan
32	nan
33	nan
34	nan
35	nan
36	nan
37	nan
38	nan
39	nan
40	nan
41	nan
42	nan
43	nan
44	nan
45	nan
46	nan
47	nan
48	nan
49	nan
50	nan
51	nan
52	nan
53	nan
54	nan
55	nan
56	nan
57	nan
58	nan
59	nan
60	nan
61	nan
Why?

**Comment by mrgloom** [comment]
Look at https://github.com/mrgloom/kaggle-dogs-vs-cats-solution/blob/master/average_results.py
Under `submissions_dir` you already need to have some predictions generated by https://github.com/mrgloom/kaggle-dogs-vs-cats-solution/blob/master/create_kaggle_submission_probability.py (for https://www.kaggle.com/c/dogs-vs-cats-redux-kernels-edition which needs probabilities )

**Comment by Jacobtom** [comment]
when i run omnisky@omnisky:~/GoogLeNet/submissions$ python create_kaggle_submission_probability.py  I get the result: "Usage: python create_kaggle_submission_probability.py deploy.prototxt model.caffemodel mean.npy <test_data_dir>"

**Comment by Jacobtom** [comment]
When I execute the following file：import os
import glob
import cv2
import caffe
import lmdb
import numpy as np
from caffe.proto import caffe_pb2

caffe.set_mode_gpu() 

#Size of images
IMAGE_WIDTH = 224
IMAGE_HEIGHT = 224

'''
Image processing helper function
'''

def transform_img(img, img_width=IMAGE_WIDTH, img_height=IMAGE_HEIGHT):

    #Histogram Equalization
    img[:, :, 0] = cv2.equalizeHist(img[:, :, 0])
    img[:, :, 1] = cv2.equalizeHist(img[:, :, 1])
    img[:, :, 2] = cv2.equalizeHist(img[:, :, 2])

    #Image Resizing
    img = cv2.resize(img, (img_width, img_height), interpolation = cv2.INTER_CUBIC)

    return img


'''
Reading mean image, caffe model and its weights 
'''
#Read mean image
mean_blob = caffe_pb2.BlobProto()
with open('/home/omnisky/GoogLeNet/input/mean.binaryproto') as f:
    mean_blob.ParseFromString(f.read())
mean_array = np.asarray(mean_blob.data, dtype=np.float32).reshape(
    (mean_blob.channels, mean_blob.height, mean_blob.width))


#Read model architecture and trained model's weights
net = caffe.Net('/home/omnisky/GoogLeNet/deploy.prototxt',
                '/home/omnisky/GoogLeNet/GoogLeNet_model/GoogLeNet_iter_18750.caffemodel',
                caffe.TEST)

#Define image transformers
transformer = caffe.io.Transformer({'data': net.blobs['data'].data.shape})
transformer.set_mean('data', mean_array)
transformer.set_transpose('data', (2,0,1))

'''
Making predicitions
'''
#Reading image paths
test_img_paths = [img_path for img_path in glob.glob("../input/test1/*jpg")]

#Making predictions
test_ids = []
preds = []
for img_path in test_img_paths:
    img = cv2.imread(img_path, cv2.IMREAD_COLOR)
    img = transform_img(img, img_width=IMAGE_WIDTH, img_height=IMAGE_HEIGHT)
    
    net.blobs['data'].data[...] = transformer.preprocess('data', img)
    out = net.forward()
    pred_probas = out['prob']

    test_ids = test_ids + [img_path.split('/')[-1][:-4]]
    preds = preds + [pred_probas.argmax()]

    print img_path
    print pred_probas.argmax()
    print '-------'

'''
Making submission file
'''
with open("../submission/submission_model_1.csv","w") as f:
    f.write("id,label\n")
    for i in range(len(test_ids)):
        f.write(str(test_ids[i])+","+str(preds[i])+"\n")
f.close() 
Terminal display：
Traceback (most recent call last):
  File "make_predictions_1.py", line 79, in <module>
    pred_probas = out['prob']
KeyError: 'prob'

**Comment by mrgloom** [comment]
You should run it with parameters like `python create_kaggle_submission_probability.py deploy.prototxt model.caffemodel mean.npy <test_data_dir>`

**Comment by Jacobtom** [comment]
when I run python create_kaggle_submission_probability.py deploy.prototxt GoogLeNet_iter_18750.caffemodel mean.npy /home/omnisky/GoogLeNet/input/test I get the result : File "create_kaggle_submission_probability.py", line 24, in <module>
    MODEL_POSTFIX= CAFFE_MODEL.split(os.sep)[-2] # not safe way
IndexError: list index out of range

**Comment by mrgloom** [comment]
Take a look how it's done here:
https://github.com/mrgloom/kaggle-dogs-vs-cats-solution/blob/master/create_submissions_for_all.sh
