### ISSUE TITLE
Could you please show us how to use SVM train the CNN extraction?

### ISSUE THREAD

**Issue by muween** [mrgloom/kaggle-dogs-vs-cats-solution#6]
> feature_extraction is folder where CNN used only as feature extractor and SVM was used for training

These days I want to do a try like this,  I would appreciate it if you could give me some tips.

**Comment by mrgloom** [comment]
This repo is no longer maintained I suggest you to use keras + sklearn for you task:
https://keras.io/applications/#fine-tune-inceptionv3-on-a-new-set-of-classes
https://scikit-learn.org/stable/modules/generated/sklearn.svm.LinearSVC.html
